spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vista360}
    username: ${DB_USERNAME:vista360}
    password: ${DB_PASSWORD:vista360}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false

  flyway:
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}

app:
  security:
    jwt:
      strategy: issuer
