-- Esquema base del servicio de registro académico de Vista 360°.
-- SQL estándar compatible con PostgreSQL y con H2 (MODE=PostgreSQL).

create table program (
    id      bigint generated by default as identity primary key,
    name    varchar(160) not null,
    faculty varchar(160) not null
);

create table academic_term (
    id         bigint generated by default as identity primary key,
    code       varchar(20) not null unique,
    name       varchar(80) not null,
    start_date date not null,
    end_date   date not null,
    is_current boolean not null default false
);

create table student (
    id         bigint generated by default as identity primary key,
    code       varchar(20) not null unique,
    document   varchar(30) not null unique,
    first_name varchar(80) not null,
    last_name  varchar(80) not null,
    email      varchar(160) not null unique,
    status     varchar(20) not null,
    program_id bigint not null references program (id)
);

create table course (
    id      bigint generated by default as identity primary key,
    code    varchar(20) not null unique,
    name    varchar(160) not null,
    credits int not null
);

create table course_offering (
    id             bigint generated by default as identity primary key,
    course_id      bigint not null references course (id),
    term_id        bigint not null references academic_term (id),
    group_code     varchar(10) not null,
    professor_name varchar(160) not null,
    constraint uq_offering unique (course_id, term_id, group_code)
);

create table enrollment (
    id                 bigint generated by default as identity primary key,
    student_id         bigint not null references student (id),
    course_offering_id bigint not null references course_offering (id),
    status             varchar(20) not null,
    enrolled_at        timestamp not null,
    grade              numeric(3, 2),
    constraint uq_enrollment unique (student_id, course_offering_id)
);

create index ix_enrollment_student on enrollment (student_id);
create index ix_offering_term on course_offering (term_id);

-- Relación asesor de acompañamiento -> estudiante asignado (base de la autorización).
create table advisor_assignment (
    id              bigint generated by default as identity primary key,
    advisor_subject varchar(120) not null,
    student_id      bigint not null references student (id),
    active          boolean not null default true,
    constraint uq_assignment unique (advisor_subject, student_id)
);

create index ix_assignment_advisor on advisor_assignment (advisor_subject);
